feat(log):Logrotate support
emqx/kuiper pull request #610
Opened 2020-11-19 06:49 UTC by EMQmyd

2020-11-20 12:54 UTC, jinfahua commented
- Does it have an option for control the log file size? For example, if the log file size reaches 100MB, then create another log file.
- Update the related docs as well.

2020-11-20 12:56 UTC, jinfahua requested changes

2020-11-20 12:56 UTC, jinfahua commented on go.mod
> +	github.com/lestrrat-go/strftime v1.0.3 // indirect
Did u use this module?

2020-11-20 12:56 UTC, jinfahua commented on go.mod
> +	github.com/rifflock/lfshook v0.0.0-20180920164130-b9218ef580f5
Did u use this module?

2020-11-20 12:58 UTC, EMQmyd commented
> * 它是否具有控制日志文件大小的选项？例如，如果日志文件大小达到100MB，则创建另一个日志文件。
> * 同时更新相关文档。

Can be divided by interval time or file size

2020-11-21 01:06 UTC, EMQmyd commented on go.mod
> +	github.com/rifflock/lfshook v0.0.0-20180920164130-b9218ef580f5
deleted

2020-11-21 01:06 UTC, EMQmyd commented on go.mod
> +	github.com/lestrrat-go/strftime v1.0.3 // indirect
yes

2020-11-23 08:38 UTC, merged