Table refactor and support continuous update
emqx/kuiper pull request #775
Opened 2021-05-08 02:37 UTC by ngjaying

#755

2021-05-08 07:27 UTC, jinfahua commented
Could you add an end-2-end SVT case?

2021-05-08 07:28 UTC, jinfahua commented on docs/en_US/sqls/tables.md
>  ```
Add a sample file content for this `table` definition.

2021-05-08 07:29 UTC, jinfahua requested changes
A sample file content...

2021-05-11 01:28 UTC, ngjaying commented
> 1. Where is the `lookup.json`?
Already in the fvt_scripts. It was created before as an input of unit tests.

2021-05-11 12:14 UTC, merged